import Head from 'next/head';
import React from 'react';
import { client, urlFor } from '../lib/client';
import Features from '../components/Features';
import { TwitterTimelineEmbed } from 'react-twitter-embed';
import New from '../components/New';
import Table from './Table';
import Maps from '../components/Maps';
import Caraosel from '../components/Caraosel';
import Hero from '../components/Hero';
import Crisasi from '../components/Crisasi';
import Link from 'next/link';

const Home = ({ products, bannerData }) => {
  return (
    <div>
      <Head>
        <title>sostsu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Caraosel />
      </div>

      <section id="about">
        <Features />
      </section>
      <div>
        <Hero />
      </div>

      <section id="colab">
        <div className="products-heading">
          <h2>コラボ　学科 </h2>
          <p>speakers of many variationals</p>
        </div>
        <div className="products-container">
          {products.map((post) => (
            <Link key={post._id} href={`/product/${post.slug.current}`}>
              <div className="max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
                <a href="#">
                  <img
                    className="rounded-t-lg w-full h-80"
                    src={urlFor(post.poster).url()}
                    alt=""
                  />
                </a>

                <div className="p-5">
                  <a href="#">
                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                      {post.title}
                    </h5>
                  </a>

                  <a
                    href="#"
                    className="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                  >
                    詳しく見る
                    <svg
                      className="ml-2 -mr-1 w-4 h-4"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fillRule="evenodd"
                        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                        clipRule="evenodd"
                      ></path>
                    </svg>
                  </a>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </section>
      <section id="table">
        <div className="max-w-7xl mx-auto px-8 sm:px-16 mb-4">
          <div className="products-heading">
            <h2>テーブル</h2>
          </div>
          <Table />
        </div>
      </section>

      <section id="articel">
        <div>
          <div className="max-w7xl mx-auto px-8 sm:px-16 mb-10">
            <div className="products-heading">
              <h2>Articel</h2>
              <div>
                <TwitterTimelineEmbed
                  sourceType="profile"
                  screenName="shirokuma014"
                  options={{ height: 600 }}
                />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="youtube">
        <div className="products-heading">
          <h2>Youtube から見る</h2>
          <New FooterBanner={bannerData && bannerData[0]} />
        </div>
      </section>

      <section id="map">
        <div className="products-heading">
          <h2>Map</h2>
          <Maps />
        </div>
      </section>
      <div id="download">
        <Crisasi />
      </div>
    </div>
  );
};
export const getServerSideProps = async () => {
  const query = '*[_type == "movie"]';
  const products = await client.fetch(query);
  const slide = '*[_type == "tipe"]';
  const slides = await client.fetch(slide);
  const bannerquery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerquery);
  const post = '*[_type == "post"][0...3]';
  const posts = await client.fetch(post);

  return {
    props: { products, bannerData, slides, posts },
  };
};
export default Home;
