import Head from 'next/head';
import { motion } from 'framer-motion';
import React from 'react';
import {
  Header,
  Banner,
  Slide,
  Product,
  Footer,
  Simple,
  FooterBanner,
} from '../components';

import { client } from '../lib/client';
const container = {
  hidden: { opacity: 1, scale: 0 },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      delayChildren: 0.3,
      staggerChildren: 0.2,
    },
  },
};

const item = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
  },
};
const Home = ({ products, bannerData, slides }) => {
  const sliderClick = (slider) => {
    alert('hello world');
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Banner />
      </div>
      <main className="max-w-7xl mx-auto px-8 sm:px-16 mb-4">
        <section>
          <div className="products-heading">
            <h2>Recommend book</h2>
            <p>speakers of many variationals</p>
          </div>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 scrollbar-hide">
            {products?.map((product) => (
              <Slide key={product._id} product={product} />
            ))}
          </div>
        </section>
      </main>
      <section>
        <div className="products-heading">
          <h2>All book </h2>
          <p>speakers of many variationals</p>
        </div>

        <div className="products-container">
          {products?.map((product) => (
            <Product key={product._id} product={product} variants={item} />
          ))}
        </div>
      </section>
      <section>
        <div className="max-w-7xl mx-auto px-8 sm:px-16 mb-4">
          <div className="products-heading">
            <h2>Category</h2>
          </div>

          <Simple slides={slides} />
        </div>
      </section>
      <section>
        <div>
          <FooterBanner FooterBanner={bannerData && bannerData[0]} />
        </div>
      </section>
    </div>
  );
};
export const getServerSideProps = async () => {
  const query = '*[_type == "movie"]';
  const products = await client.fetch(query);
  const slide = '*[_type == "tipe"]';
  const slides = await client.fetch(slide);
  const bannerquery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerquery);

  return {
    props: { products, bannerData, slides },
  };
};
export default Home;
